### ISSUE TITLE
env values have trailing new lines

### ISSUE THREAD

**Issue by barrykaplan** [garronej/vite-envs#15]
I'm seeing that my envs have trailing newlines. This cause errors with boolean. I'm still looking at this, but if you have any ideas...

![image](https://github.com/garronej/vite-envs/assets/92334816/c6968ed1-5d67-40bf-bc0b-a098cddeb0d6)

started via
```
docker run --rm -p 3010:80 \
    -e API_URL="http://localhost:3000" \
    -e ENVIRONMENT="staging" \
    -e FARO_SESSIONTRACKING_ENABLED="true" \
    -e FARO_SESSIONTRACKING_SAMPLINGRATE="1" \
    -e FFLAGS__SHOW_ENTITY_IDS="false" \
    reli-ui
```

Dockerfile
```
FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html

COPY dist/  .
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT sh -c "./vite-envs.sh && nginx -g 'daemon off;'"
```

**Comment by barrykaplan** [comment]
I can't tell where the env's get encoded. In the meantime I'm just trimming them on pulled from import.meta.env.

**Comment by barrykaplan** [comment]
I see different behavior in different runtime environments: docker on linux mint, and k8s pod on azure aks.

local:  When running locally with docker, the index.html is created correctly.
azure: When running in k8s, the index.html has embedded newlines in the base64 encoded values. (The script does _not_ use `base64 -w 0)

Within the running the container I modified the script to write to `index-2.html` and executed it in both environments.

azure: Produced the the exact same output as `index.html`
local: Produced different output from `index.html`, but not quite the same as on azure. 

Locally, one difference is newlines in the generated script

index.html
```
 <script data-script-description="Environment variables injected by vite-envs">
  var envWithValuesInBase64 = {
  "BASE_URL": "Lw==",
  "MODE": "cHJvZHVjdGlvbg==",
  "DEV": "ZmFsc2U=",
  "PROD": "dHJ1ZQ==",
  "ENVIRONMENT": "ZGV2ZWxvcG1lbnQ=",
  "VERSION": "MC4wLjA=",
  "API_URL": "aHR0cDovL2xvY2FsaG9zdDozMDAw",
  "FFLAGS__SHOW_ENTITY_IDS": "ZmFsc2U=",
  "FARO_TOKEN": ""
};
  var env = {};
  Object.keys(envWithValuesInBase64).forEach(function (name) {
    env[name] = new TextDecoder().decode(
      Uint8Array.from(
        atob(envWithValuesInBase64[name]),
        c => c.charCodeAt(0))
    );
  });
  window.__VITE_ENVS = env;
</script>
```

index-2.html
```
    <script data-script-description="Environment variables injected by vite-envs">
      var envWithValuesInBase64 = {"BASE_URL":"Lwo=","MODE":"cHJvZHVjdGlvbgo=","DEV":"ZmFsc2UK","PROD":"dHJ1ZQo=","ENVIRONMENT":"ZGV2ZWxvcG1lbnQK","VERSION":"MC4wLjAK","API_URL":"aHR0cDovL2xvY2FsaG9zdDozMDAwCg==","FFLAGS__SHOW_ENTITY_IDS":"ZmFsc2UK","FARO_TOKEN":"RkFST19UT0tFTgo="};
      var env = {};
      Object.keys(envWithValuesInBase64).forEach(function (name) {
        env[name] = new TextDecoder().decode(
          Uint8Array.from(
            atob(envWithValuesInBase64[name]),
            c => c.charCodeAt(0))
        );
      });
      window.__VITE_ENVS = env;
    </script>
```

The index-2.html is has the same form as that on azure -- no newlines in the `var envWithValuesInBase64` object.

On azure, while the index.html and index-2.html are identical, some of encoded values in `envWithValuesInBase64` have embedded newlines which don't decode properly.

**Comment by garronej** [comment]
Hey @barrykaplan,  
I'm very sorry I didn't see your issue, for some reason I had notification off on this repo.   
I'll def look into it

**Comment by garronej** [comment]
Not forgotten, just didn't had time

**Comment by garronej** [comment]
@barrykaplan, It's fixed. Sorry it took so long. Thanks a lot for reporting.
