### ISSUE TITLE
[BUG] Environment variables are not accessible from the .env file

### ISSUE THREAD

**Issue by wowblvck** [garronej/vite-envs#19]
### Info

1. Version: `4.0.15 (latest)`.
2. Latest working version: `4.0.10`.
3. Used library or framework: `React (18.2.0)`.
4. Vite configuration: 
```tsx
export default defineConfig(({
    mode
}) => {
    const env = loadEnv(mode, process.cwd(), '');
    return {
        base: env.NODE_ENV === 'production' ? '/production' : '/',
        plugins: [
            react(),
            mkcert(),
            webfontDownload(),
            svgr(),
            ValidateEnv(),
            viteEnvs({
                declarationFile: '.env.example',
            }),
        ],
    },
});
```
5. Declaration file (`.env.example`):
```console
VITE_KEY_1=

VITE_KEY_2=

...etc
```
4. Environment variable file (`.env`): 
```console
VITE_KEY_1=some_key_1
VITE_KEY_2=some_key_2
```

### Description

After updating to version `4.0.15` (previously updated to `4.0.13` and caught the same bug), environment variables are read from the `.env.example` file, and not from the `.env` file as it was in version 4.0.10. As a result, the values of environment variables are empty (null string).

### Reproduce

1. Reproduce for version `4.0.15`: [4.0.15](https://stackblitz.com/edit/vitejs-vite-bpn1w3?file=src%2Fmain.tsx)
2. Reproduce for version `4.0.10`: [4.0.10](https://stackblitz.com/edit/vitejs-vite-xkvtcw?file=src%2Fmain.tsx)

See output in console

**Comment by garronej** [comment]
Hello @wowblvck,  
Thank you for reporting and sory about the bad experience.  

I'll adress this today

**Comment by wowblvck** [comment]
Hello @garronej,

My pleasure. Thank you for your product, it is an integral part of our development)

**Comment by garronej** [comment]
Allright @wowblvck,  
Thanks for the feedback.  
I'm quite surprised that this project is used already because I havent shared it anywhere yet.  
It has some stars only because I repurposed an older project [cra-envs](https://github.com/garronej/cra-envs).  
It's a bit cahotic at the moment, time for me to adjust the bugs that are reported to me by the few users we have.

**Comment by wowblvck** [comment]
@garronej 

Our DevOps developer uses vite-envs for deployment.

**Comment by garronej** [comment]
@wowblvck It should be fixed in the last version!
