### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by melishev** [garronej/vite-envs#29]
Hi, sorry to post a question here, but I don't have a lot of time to figure out how the plugin works.

I'm trying to understand how to work with the plugin during development. I have everything set up for build and docker. Everything works great. But when I try to run the project locally through: “dev": ‘vite’, the variables I'm trying to get import.meta.env.FOO === undefined. Although when I call __VITE_ENVS through the developer console I get the whole list of variables and it is valid with the data that I would like to get instead of undefined.

Can you briefly describe how to proceed in dev mode, or provide a minimal demo?

**Comment by garronej** [comment]
Hello @melishev,  

It's supposed to work. The plugin is supposed to be transparent. 
Everything should work like when you don't have the plugin setup, and just enable you to inject the variables by running the bash script.  

There is a demo repo here: https://github.com/garronej/vite-envs-starter
And a demo video here: https://www.youtube.com/watch?v=wsY7VDUIZM0  

One thing that does not work is web workers. Beside this if it does not work please share some aditional informations I'll help you debug or fix the issue on my end if there's any.

**Comment by melishev** [comment]
@garronej 
Here is link to reproduction: https://github.com/melishev/vite-envs-demo

I don't think I ever found an explanation of this case in the documentation

**Comment by garronej** [comment]
Thank you for the repro @melishev,  

The important bit of context I was missing was that you're using vue.  

I released a patch for supporting it: `vite-envs@4.4.4`  

PS: Don't forget to add `"postinstall": "vite-envs update-types",` in the `scripts` of your `package.json`. It was missing in your repo.
